### PR TITLE
Introspective theorems, definition

### PR DESCRIPTION
**Pull request by metakunt**
Trying to define the introspective relation. Apparently we need some polynomial results.

Would you please take a look at it? I have no idea what the best definition is, so I've left it blank. I've never dealt with structures or definitions of structures.

But certainly we will need polynomials over $\mathbb{Z}$ at the very least.

### CODE REVIEW

**Comment by tirix** [comment]
I only have very short time today, so I'm providing only part of this definition.
```
INTRO = ( p e. NN , r e. NN |-> 
  { <. e , f >. | [. ( Poly1 ` ZZring ) / z ]. ( e e. NN0 /\ f e. ( Base ` z ) /\ ( ... ) ( ||r ` z ) ( ( r ( .g ` ( mulGrp ` z ) ) ( var1 ` ZZring ) ) ( -g ` z ) ( ( algSc ` z ) ` 1 ) ) ) } )
```
So we have:
- `( p e. NN , r e. NN |-> ` an operation mapping two positive integers `p` and `r` to...
- ` { <. e , f >. | ` the relation between `e` and `f`, such that `e` and `f` are related when...
- (``[. ( Poly1 ` ZZring ) / z ].`` this is a common shortcut for definitions. Here, `z` will stand for the univariate polynomials on `ZZ`)
- `e e. NN0` `e` is a non-negative number, and...
- ``f e. ( Base ` z )`` `f` is a polynomial over `ZZ`, and ...
- ` (...) ` this is the transformation on `f` I still need to build !
- `` ( ||r ` z ) `` divides, for the `ZZ` polynomials...
- `` ( r ( .g ` ( mulGrp ` z ) ) ( var1 ` ZZring ) ) `` $X^r$...
- `` ( -g ` z ) `` minus, for the `ZZ` polynomials...
- `` ( ( algSc ` z ) ` 1 ) `` $1$, seen as a `ZZ` polynomial.

**Comment by tirix** [comment]
Where does the "introspective relation" come from?
If it's specific to AKS, maybe it could rather be named `IntroAKS` or something similar.

**Comment by metakunt** [comment]
Definition is from the original paper.
https://www.cse.iitk.ac.in/users/manindra/algebra/primality_v6.pdf

Yeah you could likely rename it, a quick google search appears to only show AKS related results or variants thereof.

**Comment by tirix** [comment]
Ok, the definition should be ready. I actually changed `z` to represent $\mathbb{Z}/\mathbb{Z}p[X]$, which is used very often in the definition.
The new part compared to the last edit is ``( z gsum ( n e. NN0 |-> ( ( ( coe1 ` f ) ` n ) .* ( n .^ e ) ) ) )``, which corresponds to $f(X^e)$
That part is actually directly taken from theorems like [`~gsummoncoe1`](https://us.metamath.org/mpeuni/gsummoncoe1.html) in AV's proof of the Cayley-Hamilton theorem, which use a lot of scaled polynomials.

**Comment by tirix** [comment]
Another theorem we probably need to formalize is Fermat's little theorem for polynomials, and its weak version:
$(X+a)^n ≡ X^n+a \mod{X^r−1,n}$

This definition is actually in the original AKS paper, but not in [the paper you were previously referring to](https://www3.nd.edu/%7eandyp/notes/AKS.pdf). Does it mean you'd like to change course?

**Comment by metakunt** [comment]
The proofs for the most part are identical modulo some small issues. I am atleast aware of some of those issues and working on formalising proofs.
Currently I am working on showing that A<B in Lemma 4.1, which needs quite a bit of analysis.
 We should prefer the easiest api's/definitions that get us to the goal.

Fermat's little theorem for polynomials should be trivial to prove. If you can formalise the statement I can likely finish the proof.

I think most lemmas are implicit in the AKS paper since they use the algebraic closure. The existence of a primitive root is explained by taking the algebra homomorphism of the r-th cyclotomic polynomial, which is irreducible. This polynomial is by construction in the closure.

We would need to develop the api for this
https://us.metamath.org/mpeuni/df-gfoo.html
which requires us to develop the api for this
https://us.metamath.org/mpeuni/df-gf.html
which requires us to ...
https://us.metamath.org/mpeuni/df-sfl.html
https://us.metamath.org/mpeuni/df-sfl1.html
https://us.metamath.org/mpeuni/cir.html


Also how good is the irreducibles api. How hard would it to prove for us that $X^2+X+1$ is irreducible in $F_2[X]$.
Similarly how hard would it for us to be able to prove that  $X^4+X^3+X^2+X+1$ is irreducible in $F_2[X]$

Do we have polynomial division in euclidean rings? Do we have euclidean rings?

I assume that we will need to develop quite a bit of api either way.

**Comment by tirix** [comment]
> Do we have euclidean rings?
> 
We do have principal ideal domains `PID`, and by [ply1pid](https://us.metamath.org/mpeuni/ply1pid.html), we know that polynomials over $\mathbb{Z}/p\mathbb{Z}$ for a prime $p$ are a PID. See also [znfld](https://us.metamath.org/mpeuni/znfld.html). 

> Do we have polynomial division in euclidean rings?
>
Yes, that would be [ply1divalg](https://us.metamath.org/mpeuni/ply1divalg.html)

> Also how good is the irreducibles api. How hard would it to prove for us that $X^2+X+1$ is irreducible in $F_2[X]$. 
> Similarly how hard would it for us to be able to prove that $X^4+X^3+X^2+X+1$ is irreducible in $F_2[X]$.
> 
We do have a definition of `Irred` and a few theorems about it, but I don't think we have much more.

> I assume that we will need to develop quite a bit of api either way.
>
Yes, as you point out, at least everything about finite fields and Galois fields is in the state of stubs and has to be developed.

**Comment by metakunt** [comment]
Well I guess the most important step will be the following theorem/inequality.
Let $r\in \mathbb{N}$ $p$ prime and let $h$ be an irreducible factor of $X^r-1$ that generates the $r$-th primitive roots. Assume $l < p$ and consider the group generated by the residuals $X,X+1,...X+l$

Let t be the degree of the $r$-th cyclotomic polynomial. Then the group generated by the residuals in $\mathbb{F}_p/h(X)$ has atleast $\binom{t+l}{t-1}$ elements.

Here I assume we will need a bit more work. We need to show that the above construction modulo irreducibles is a field. We also need to show that the multiplicative group (of a field) is cyclic.
We also need to show that the cardinality of a group is bounded by the order of their elements.
We need to show that $h(X)$ is irreducible in $\mathbb{F}_p[X]$.

I assume there is some work to do ;)

**Comment by tirix** [comment]
> We also need to show that the cardinality of a group is bounded by the order of their elements.

This should be trivial by [oddvds2](https://us.metamath.org/mpeuni/oddvds2.html).
The rest, not so much!

**Comment by tirix** [comment]
> The multiplicative group (of a field) is cyclic.

You mean, for those specific fields?

**Comment by metakunt** [comment]
No this is true in general and the proof mimics the idea, see
https://math.stackexchange.com/questions/59903/finite-subgroups-of-the-multiplicative-group-of-a-field-are-cyclic

The idea is very simple, we generate two groups and use some functions to generate mappings, we can then make estimations on the size of the groups and arrive to a contradiction. However sometimes the proof is easier to follow in one paper than in the other, but for the most part we should be able to be fine to calculate in $F_p[X]/(X^r-1)$

Recall that, given some assumptions, we want to construct a group and then make estimations about its size.

The idea is quite simple, calculate some polynomial congruences modulo certain polynomials. The residue groups grow quite fast so that all numbers are covered. We just have to go above a certain number and the groups generated will both be too small and too big, if $n$ is not a prime power.

I'd like to invite you to a call so that we can discuss it in a more detailed way. Let me know if you are interested.

**Comment by tirix** [comment]
> Fermat's little theorem for polynomials should be trivial to prove. If you can formalise the statement I can likely finish the proof.

I've provided a proof of similar statement in [set.mm#4099](https://github.com/metamath/set.mm/pull/4099).

**Pull request merged**
