### PR TITLE
Markup fixes

### PR DESCRIPTION
**Pull request by jkingdon**
1. Use a shorter title because the site generation code truncates

2. Fix link syntax

### CODE REVIEW

**Comment by tirix** [comment]
Now the _build_ part of the CI is also run on the PR, but not the _deploy_, so you can check the changes.

**Comment by tirix** [comment]
I've invited you as a collaborator, so you can merge your own PR when they are ready.

**Comment by jkingdon** [comment]
> Now the _build_ part of the CI is also run on the PR, but not the _deploy_, so you can check the changes.

Ah, got it. I seem to be able to find the built files in an artifact download.

**Comment by tirix** [comment]
If you prefer you can also build locally, the builder is [metamath-blueprints-rs](https://github.com/tirix/metamath-blueprints-rs).

**Pull request merged**
