### PR TITLE
First attempt at formalizing AKS

### PR DESCRIPTION
**Pull request by metakunt**
Hey @tirix that is a cool tool. Here I have made an attempt at formalizing AKS.

Since I yet don't know the notations for your tool I have just written it best effort. Feel free to edit it.

### CODE REVIEW

**Comment by tirix** [comment]
This tool is just a few days old and not yet well documented! :)
The admissible states for the theorems are:
- `Draft`,
- `ReadyForStmt`,
- `StmtFormalized`,
- `ReadyForProof`,
- `Formalized`

I consider the hypotheses are part of the statement, so if they are not ready the statement is not yet formalized.

**Comment by metakunt** [comment]
I have to rename my branch as I've pushed onto master

**Comment by tirix** [comment]
Is it OK if I have a try at building the blueprint?

**Comment by metakunt** [comment]
Of course! That would be very much appreciated.

**Pull request closed without merging**
